sudo: required
services:
  - docker

before_install:
  - docker build -t edwrenbeck/docker-react -f Dockerfile.dev .

script:
  - docker run edwrenbeck/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react2"
  env: "DockerReact2-env"
  bucket_name: "elasticbeanstalk-us-east-2-113178840441"
  bucket_path: "docker-react2"
  on:
    branch: master
  access_key_id: $aws_access_key
  secret_access_key:
    secure: "$aws_access_secret"
