sudo: required
services:
  - docker

before_install:
  - docker build -t edwrenbeck/docker-react -f Dockerfile.dev .

script:
  - docker run edwrenbeck/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-113178840441"
  bucket_path: "docker-react"
  on:
    branch: master
